// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcylDS2axBPlV88FUmP5AdXCmBedy371M',
    appId: '1:519605605827:web:e29719afafa50208aa9976',
    messagingSenderId: '519605605827',
    projectId: 'gsc-project-f6775',
    authDomain: 'gsc-project-f6775.firebaseapp.com',
    storageBucket: 'gsc-project-f6775.firebasestorage.app',
    measurementId: 'G-LGE44J1PN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-3t1i5KZ6qGErrqgOziv_-YslVFrB2Y',
    appId: '1:519605605827:android:fe1b18e398ce6bd9aa9976',
    messagingSenderId: '519605605827',
    projectId: 'gsc-project-f6775',
    storageBucket: 'gsc-project-f6775.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHkNWZDJHhy6Pf4cuKSDxikGfoi_QZ7X4',
    appId: '1:519605605827:ios:06a7b64a9770ce78aa9976',
    messagingSenderId: '519605605827',
    projectId: 'gsc-project-f6775',
    storageBucket: 'gsc-project-f6775.firebasestorage.app',
    iosBundleId: 'com.example.gscProject',
  );
}
